[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[theme]
base = "dark"
primaryColor = "#DEDEDE"
backgroundColor = "#0C0C0C"
secondaryBackgroundColor = "#111111"
textColor = "#DEDEDE"
font = "sans serif"

[browser]
gatherUsageStats = false
