[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[theme]
base = "dark"
primaryColor = "#FFFFFF"
backgroundColor = "#09090F"
secondaryBackgroundColor = "#0C0C14"
textColor = "#D0D0E0"
font = "sans serif"

[browser]
gatherUsageStats = false
